global:
  hosts:
    domain: localhost
    externalIP: "127.0.0.1"
    https: false
    email: zinb9419@gmail.com
  service:
    http:
      port: 8080
  rails:
    bootsnap:
      enabled: false

certmanager:
  install: false

certmanager-issuer:
  enabled: true
  email: zinb9419@gmail.com

nginx-ingress:
  enabled: true
  controller:
    service:
      type: LoadBalancer

gitlab-runner:
  install: false

prometheus:
  install: false

gitlab:
  webservice:
    minReplicas: 1
    maxReplicas: 1

  sidekiq:
    minReplicas: 1
    maxReplicas: 1

  gitlab-shell:
    minReplicas: 1
    maxReplicas: 1

  gitaly:
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
      limits:
        cpu: 200m
        memory: 400Mi

registry:
  hpa:
    minReplicas: 1
    maxReplicas: 1