global:
  edition: ce
  hosts:
    domain: localhost
    externalIP: "127.0.0.1"
    https: false
  ingress:
    configureCertmanager: false
    class: "traefik"
    path: '/gitlab/'  # Set the base path
    pathType: Prefix
    annotations:
      traefik.ingress.kubernetes.io/rule-type: "PathPrefixStrip"
  appConfig:
    gitlab:
      gitlab_relative_url_root: '/gitlab'

certmanager:
  install: false

nginx-ingress:
  enabled: false

gitlab-runner:
  install: false

# Reduce resource usage for local development
postgresql:
  install: true
  postgresqlUsername: gitlab
  postgresqlDatabase: gitlab
  postgresqlPassword: "gitlabpassword"
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 512Mi

redis:
  install: true
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 256Mi

minio:
  install: true
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 256Mi

gitlab:
  webservice:
    minReplicas: 1
    maxReplicas: 1
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 300m
        memory: 800Mi
    extraEnv:
      GITLAB_RELATIVE_URL_ROOT: '/gitlab'

  sidekiq:
    minReplicas: 1
    maxReplicas: 1
    resources:
      requests:
        cpu: 50m
        memory: 350Mi
      limits:
        cpu: 100m
        memory: 500Mi

  gitlab-shell:
    minReplicas: 1
    maxReplicas: 1
    resources:
      requests:
        cpu: 50m
        memory: 150Mi
      limits:
        cpu: 100m
        memory: 200Mi

  gitaly:
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
      limits:
        cpu: 200m
        memory: 400Mi
certmanager:
  install: false 
prometheus:
  install: false 
