global:
  edition: ce
  hosts:
    domain: localhost
    externalIP: "127.0.0.1"
    https: false
    email: zinb9419@gmail.com
    relativePath: /gitlab

certmanager:
  install: false

certmanager-issuer:
  enabled: false
  email: zinb9419@gmail.com


nginx-ingress:
  enabled: true
  controller:
    config:
      use-forwarded-headers: "true"
    ingressClassResource:
      name: gitlab-nginx
      enabled: true
      default: false
    admissionWebhooks:
      enabled: false

gitlab-runner:
  install: false

prometheus:
  install: false 

postgresql:
  install: true
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 512Mi

redis:
  install: true
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 256Mi

minio:
  install: true
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 256Mi

gitlab:
  webservice:
    minReplicas: 1
    maxReplicas: 1
    deployments:
      default:
        ingress:
          path: /gitlab
          pathType: Prefix
    ingress:
      enabled: true
      path: /gitlab(/|$)(.*)
      pathType: Prefix
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$2
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
        nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
        nginx.ingress.kubernetes.io/proxy-connect-timeout: "15"
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 300m
        memory: 800Mi
    extraEnv:
      GITLAB_RELATIVE_URL_ROOT: '/gitlab'
    workhorse:
      extraArgs:
        - --relative-url-root=/gitlab
  task-runner:
    backups:
      extraArgs: ["--relative-url-root=/gitlab"]
  migrations:
    extraEnv:
      GITLAB_RELATIVE_URL_ROOT: '/gitlab'

  sidekiq:
    minReplicas: 1
    maxReplicas: 1
    resources:
      requests:
        cpu: 50m
        memory: 350Mi
      limits:
        cpu: 100m
        memory: 500Mi
    extraEnv:
      GITLAB_RELATIVE_URL_ROOT: '/gitlab'

  gitlab-shell:
    minReplicas: 1
    maxReplicas: 1
    resources:
      requests:
        cpu: 50m
        memory: 150Mi
      limits:
        cpu: 100m
        memory: 200Mi

  gitaly:
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
      limits:
        cpu: 200m
        memory: 400Mi

registry:
  hpa:
    minReplicas: 1
    maxReplicas: 1
